language: java
#ruby: 2.7.4
jdk: 17
addons:
  sonarcloud:
    organization: "test-runs-tci"
    token: $SONAR_TOKEN
script:
#  - bundle exec rspec --format documentation
  - sleep 3
  - sonar-scanner

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
