# TEST RUN
#language: ruby
language: php
php: 8.1.2
jdk: openjdk17
addons:
  sonarcloud:
    organization: "test-runs-tci"
    token: $SONAR_TOKEN

#cache: bundler

# Setup JDK 17 # 
before_install:
  - sudo apt-get -y remove default-jdk
  - sudo apt -y autoremove
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17.0.2-open
  - sdk use java 17.0.2-open
  - java -version
script:
  #- bundle exec rspec --format documentation
  - sleep 3
  - sonar-scanner

jobs:
  include:
    - os: linux
      dist: jammy
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
