# TEST RUN
#language: ruby
language: php
php: 8.0.0
jdk: openjdk17
addons:
  sonarcloud:
    organization: "test-runs-tci"
    token: $SONAR_TOKEN

#cache: bundler

script:
  #- bundle exec rspec --format documentation
  - sleep 3
  - sonar-scanner

jobs:
  include:
    - os: linux
      dist: jammy
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
