language: ruby
ruby: 2.7.4

script:
  - bundle exec rspec --format documentation
  - sleep 2

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial